import ClientOnly from '@/components/ClientOnly'
import ProfileModal from '@/components/ProfileModal/ProfileModal'
import AuthProvider from '@/providers/AuthProvider'
import ToastProvider from '@/providers/ToastProvider'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Session } from 'next-auth'

export const metadata: Metadata = {
  title: 'Dashboard | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: Session
}) {
  return (
    <html lang="en">
      <AuthProvider session={session}>
        <body>
          <ClientOnly>
            <ToastProvider />
            <ProfileModal />
          </ClientOnly>
          {children}
        </body>
      </AuthProvider>
    </html>
  )
}
